package com.example.onelabpractice1.enums;

public enum Response {
    USER_REGISTERED_SUCCESSFULLY, ADMIN_REGISTERED_SUCCESSFULLY,
    PHONE_ALREADY_EXIST, PHONE_NUMBER_NOT_FOUND, BALANCE_IS_NOT_ENOUGH,
    OK, FAILED,
    DELETED_SUCCESSFULLY, USER_UPDATED
}
